name: 'Trigger Release Workflow'
description: 'Triggers the release workflow for eligible branches'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  ref:
    description: 'Git ref to release from'
    required: true
  sha:
    description: 'Commit SHA to release'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          // Normalize branch name by removing refs/heads/ prefix
          const branch = context.ref.replace('refs/heads/', '');
          
          // Only trigger for beta/main branches
          if (!['beta', 'main'].includes(branch)) {
            console.log(`Branch ${branch} not eligible for release workflow`);
            return;
          }

          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'workflow_create_release.yml',
            ref: context.ref,
            inputs: {
              trigger_sha: context.sha,
              source_branch: branch  // Use normalized branch name
            }
          });
          
          console.log(`Triggered release workflow for ${branch} at ${context.sha}`);
