name: 'Queue Release'
description: 'Adds a commit to the release queue via PR'

inputs:
  github_token:
    required: true
  sha:
    required: true
  branch:
    required: true

outputs:
  queue_position:
    description: 'Position in queue'
    value: ${{ steps.queue.outputs.position }}
  estimated_time:
    description: 'Estimated time until release'
    value: ${{ steps.queue.outputs.estimated_time }}
  pr_number:
    description: 'Created PR number'
    value: ${{ steps.create_pr.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - id: setup
      shell: bash
      run: |
        # Create a new branch for the queue update
        QUEUE_BRANCH="queue-update-$(date +%s)"
        git checkout -b $QUEUE_BRANCH
        echo "branch=$QUEUE_BRANCH" >> $GITHUB_OUTPUT

    - id: queue
      shell: bash
      run: |
        # Determine queue file based on branch
        QUEUE_FILE=".github/release_queue/${{ inputs.branch }}.json"
        
        # Create queue directory if needed
        mkdir -p .github/release_queue
        
        # Create or read queue file
        if [ ! -f "$QUEUE_FILE" ]; then
          echo '{"items":[]}' > "$QUEUE_FILE"
        fi
        
        # Add new item to queue
        jq --arg sha "${{ inputs.sha }}" \
           --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
           '.items += [{"commit": $sha, "date": $date}]' \
           "$QUEUE_FILE" > "${QUEUE_FILE}.tmp" && mv "${QUEUE_FILE}.tmp" "$QUEUE_FILE"
        
        # Calculate queue position and estimated time
        POSITION=$(jq '.items | length' "$QUEUE_FILE")
        
        if [[ "${{ inputs.branch }}" == "beta" ]]; then
          EST_DAYS=0
          MIN_ITEMS=10
        else
          EST_DAYS=14
          MIN_ITEMS=15
        fi
        
        echo "position=$POSITION" >> $GITHUB_OUTPUT
        echo "estimated_time=$EST_DAYS days" >> $GITHUB_OUTPUT
        echo "remaining=$((MIN_ITEMS - POSITION))" >> $GITHUB_OUTPUT

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "action@github.com"

    - name: Sign Commit
      shell: bash
      run: |
        git add .github/release_queue/
        git commit -S -m "📦 Queue release for ${{ inputs.sha }}
        
        Queue Status:
        - Position: ${{ steps.queue.outputs.position }}
        - Items needed: ${{ steps.queue.outputs.remaining }} more
        - Estimated time: ${{ steps.queue.outputs.estimated_time }}"

    - name: Push Changes
      shell: bash
      run: |
        git push origin ${{ steps.setup.outputs.branch }}

    - id: create_pr
      shell: bash
      run: |
        PR_TITLE="📦 Update Release Queue: Position ${{ steps.queue.outputs.position }}"
        PR_BODY="## Release Queue Update
        
        🎯 Adding commit \`${{ inputs.sha }}\` to the release queue.
        
        ### Queue Status
        - Current Position: ${{ steps.queue.outputs.position }}
        - Items Needed: ${{ steps.queue.outputs.remaining }} more
        - Estimated Release Time: ${{ steps.queue.outputs.estimated_time }}
        
        > This PR was automatically created by the release queue system.
        > Once merged, this commit will be included in the next release batch."
        
        PR_NUMBER=$(gh pr create \
          --title "$PR_TITLE" \
          --body "$PR_BODY" \
          --base "${{ inputs.branch }}" \
          --head "${{ steps.setup.outputs.branch }}" \
          --label "release-queue" \
          --label "automated-pr" \
          --json number -q .number)
        
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Request Review
      if: steps.create_pr.outputs.pr_number
      shell: bash
      run: |
        gh pr review ${{ steps.create_pr.outputs.pr_number }} --approve
      env:
        GH_TOKEN: ${{ inputs.github_token }}
