[package]
name = "github-workflow-scripts"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "step-check-workflow-states"
path = "src/bin/step_check_workflow_states.rs"

[[bin]]
name = "step-check-artifacts"
path = "src/bin/step_check_artifacts.rs"

[[bin]]
name = "step-check-base-image"
path = "src/bin/step_check_base_image.rs"

[[bin]]
name = "step-setup-docker-env"
path = "src/bin/step_setup_docker_env.rs"

[[bin]]
name = "step-build-image"
path = "src/bin/step_build_image.rs"

[[bin]]
name = "step-verify-docker-image"
path = "src/bin/step_verify_docker_image.rs"

[dependencies]
anyhow = "1.0"
octocrab = "0.32"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
