version: '3.8'

services:

  dev:

    image: cmoe640/dev-environment:latest  # Pull from Docker Hub

    container_name: dev-environment

    ports:
      - "8080:8080" # VS Code
      - "3000-3010:3000-3010" # Frontend apps
      - "8000-8010:8000-8010" # Backend services

    volumes:
      - ./projects:/usr/src/projects # Mount projects
      - ~/.ssh:/home/devuser/.ssh:ro # Mount SSH keys
      - ~/.gitconfig:/home/devuser/.gitconfig:ro # Mount Git config
      - vscode-server:/home/devuser/.vscode-server # Persist VS Code settings
      - npm-cache:/home/devuser/.npm # Persist NPM cache
      - cargo-cache:/home/devuser/.cargo # Persist Cargo cache
      - go-cache:/home/devuser/go # Persist Go cache

    restart: unless-stopped

    stdin_open: true # Add this line

    tty: true        # Add this line

volumes:

  vscode-server:

  npm-cache:

  cargo-cache:

  go-cache:

