name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'projects/**/frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull dev environment image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dev-environment:latest

      - name: Run tests in dev environment
        uses: docker:// ${{ secrets.DOCKERHUB_USERNAME }}/dev-environment:latest
        with:
          args: bash -c "cd /usr/src/projects/$(echo ${{ github.repository }} | cut -d '/' -f 2)/frontend && npm install && npm test"
        env:
          REMOTE_REPO_TOKEN: ${{ secrets.REMOTE_REPO_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
