name: 'Version Determiner'
description: 'Determines the next version based on Git tags'

outputs:
  new_version:
    description: 'The determined new version'
    value: ${{ steps.versioning.outputs.new_version }}

runs:
  using: 'composite'
  steps:
    - id: versioning
      shell: bash
      run: |
        # Get latest tag
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0-beta.0")
        echo "Latest tag: $latest_tag"
        
        # Parse version components
        if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)-beta\.([0-9]+)$ ]]; then
          major="${BASH_REMATCH[1]}"
          minor="${BASH_REMATCH[2]}"
          patch="${BASH_REMATCH[3]}"
          beta="${BASH_REMATCH[4]}"
          
          # Increment beta number
          new_beta=$((beta + 1))
          new_version="v$major.$minor.$patch-beta.$new_beta"
        else
          # Start with beta.1 if no valid tag found
          new_version="v0.1.0-beta.1"
        fi
        
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
        echo "Determined new version: $new_version"
