name: 'Create Release'
description: 'Creates a new release with proper versioning and tags'

inputs:
  version:
    description: 'Version to release'
    required: true
  prerelease:
    description: 'Whether this is a prerelease'
    required: true
  github_token:
    description: 'GitHub token for creating release'
    required: true
  bot_gpg_private_key:
    description: 'Bot GPG private key for signing'
    required: true
  bot_gpg_passphrase:
    description: 'Bot GPG passphrase'
    required: true
  bot_github_token:
    description: 'Bot GitHub token'
    required: true
  bot_email:
    description: 'Bot email for git config'
    required: true
  bot_name:
    description: 'Bot name for git config'
    required: true
  bot_domain:
    description: 'Bot domain for config'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for proper versioning

    - name: Extract assets from Docker image
      shell: bash
      run: |
        # Use version from inputs for Docker tag
        docker pull cmo640/dev-environment:${{ inputs.version }}
        
        # Create release assets directory
        mkdir -p release_assets
        
        # Extract files directly from container
        docker create --name temp_container cmo640/dev-environment:${{ inputs.version }}
        docker cp temp_container:/app/. ./release_assets/
        docker rm temp_container
        
        # Create archive
        cd release_assets
        tar -czf ../dev-environment.tar.gz .
        cd ..
        sha256sum dev-environment.tar.gz > checksum.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        name: "${{ inputs.prerelease && 'Beta' || 'Stable' }} Release ${{ inputs.version }}"
        body: |
          ## Release Notes
          
          ### Docker Image
          ```
          docker pull cmo640/dev-environment:${{ inputs.version }}
          ```
          
          ### SHA256 Checksums
          ```
          $(cat checksum.txt)
          ```
        prerelease: ${{ inputs.prerelease }}
        files: |
          dev-environment.tar.gz
          checksum.txt
        draft: false
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Import GPG key
      shell: bash
      run: |
        echo "${{ inputs.bot_gpg_private_key }}" | gpg --batch --import
        echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
        gpg-connect-agent reloadagent /bye
      env:
        GPG_TTY: $(tty)
        GPG_PASSPHRASE: ${{ inputs.bot_gpg_passphrase }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{ inputs.bot_name }}"
        git config --global user.email "${{ inputs.bot_email }}"
        git config --global user.signingkey "${{ inputs.bot_gpg_private_key }}"
        git config --global commit.gpgsign true

    - name: Update Documentation Links
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.bot_github_token }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        BOT_NAME: ${{ inputs.bot_name }}
        BOT_DOMAIN: ${{ inputs.bot_domain }}
      run: |
        RELEASE_TAG=$(gh release list -L 1 | cut -f1)
        sed -i "s|releases/[^/]*/download/|releases/latest/download/|g" docs/QUICK_START.md
        git config user.name "${BOT_NAME}"
        git config user.email "${BOT_EMAIL}@${BOT_DOMAIN}"
        git add docs/QUICK_START.md
        git commit -S -m "docs: update distribution links to ${RELEASE_TAG}" || true
        git push origin HEAD:${{ github.ref_name }}