name: 'Create Release'
description: 'Creates a new release with packaged application state'

inputs:
  version:
    description: 'Version to release'
    required: true
  prerelease:
    description: 'Whether this is a prerelease'
    required: true
  github_token:
    description: 'GitHub token for creating release'
    required: true
  bot_gpg_private_key:
    description: 'Bot GPG private key for signing'
    required: true
  bot_gpg_passphrase:
    description: 'Bot GPG passphrase'
    required: true
  bot_github_token:
    description: 'Bot GitHub token'
    required: true
  bot_email:
    description: 'Bot email for git config'
    required: true
  bot_name:
    description: 'Bot name for git config'
    required: true
  bot_domain:
    description: 'Bot domain for config'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }} # Prevents branch deletion
        clean: false # Preserves local changes

    - name: Package Release Assets
      shell: bash
      run: |
        # Create staging area
        mkdir -p release_assets
        
        # Copy application code and configs
        cp -r distributions startup docs release_assets/
        
        # Include Dockerfile for users who want to build locally
        cp Dockerfile* release_assets/ 2>/dev/null || true
        cp docker-compose*.yml release_assets/ 2>/dev/null || true
        
        # Package everything
        cd release_assets
        tar -czf ../dev-environment.tar.gz .
        cd ..
        
        # Generate checksums
        sha256sum dev-environment.tar.gz > checksum.txt

    - name: Validate Version
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [[ -z "$VERSION" ]]; then
          echo "::error::No version provided. Cannot create release without a tag."
          exit 1
        fi
        
        # Remove 'v' prefix if present for consistency
        VERSION=${VERSION#v}
        echo "VALIDATED_VERSION=v${VERSION}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VALIDATED_VERSION }}
        name: "${{ inputs.prerelease && 'Beta' || 'Stable' }} Release ${{ env.VALIDATED_VERSION }}"
        body: |
          ## Release Notes
          ${{ steps.process.outputs.notes }}
          
          ### Distributions
          This release includes:
          - Complete development environment configuration
          - Docker setup files for containerized usage
          - Direct deployment scripts
          
          ### Installation
          ```bash
          # Download and extract
          curl -LO https://github.com/BA-CalderonMorales/dev-environment/releases/download/${{ env.VALIDATED_VERSION }}/dev-environment.tar.gz
          tar xzf dev-environment.tar.gz
          
          # Optional: Build Docker container locally
          docker build -t dev-environment:${{ env.VALIDATED_VERSION }} .
          ```
          
          ### Verification
          SHA256 Checksums:
          ```
          $(cat checksum.txt)
          ```
          
          ### Environment Info
          - Type: ${{ inputs.prerelease && 'Beta' || 'Production' }}
          - Released: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - Branch: ${{ github.ref_name }}
          
          For setup instructions, see our [Quick Start Guide](docs/QUICK_START.md).
        
        prerelease: ${{ inputs.prerelease }}
        files: |
          dev-environment.tar.gz
          checksum.txt
        draft: false
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Import GPG key
      shell: bash
      run: |
        echo "${{ inputs.bot_gpg_private_key }}" | gpg --batch --import
        echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
        gpg-connect-agent reloadagent /bye
      env:
        GPG_TTY: $(tty)
        GPG_PASSPHRASE: ${{ inputs.bot_gpg_passphrase }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{ inputs.bot_name }}"
        git config --global user.email "${{ inputs.bot_email }}"
        git config --global user.signingkey "${{ inputs.bot_gpg_private_key }}"
        git config --global commit.gpgsign true

    - name: Update Documentation Links
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.bot_github_token }}
        BOT_EMAIL: ${{ inputs.bot_email }}
        BOT_NAME: ${{ inputs.bot_name }}
        BOT_DOMAIN: ${{ inputs.bot_domain }}
      run: |
        # Keep documentation pointing to latest release for easier user access
        RELEASE_TAG=$(gh release list -L 1 | cut -f1)
        sed -i "s|releases/[^/]*/download/|releases/latest/download/|g" docs/QUICK_START.md
        
        # Update documentation with bot credentials for tracking
        git config user.name "${BOT_NAME}"
        git config user.email "${BOT_EMAIL}@${BOT_DOMAIN}"
        git add docs/QUICK_START.md
        git commit -S -m "docs: update distribution links to ${RELEASE_TAG}" || true
        git push origin HEAD:${{ github.ref_name }}