blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/BA-CalderonMorales/dev-environment/discussions
    about: Please ask and answer questions here. 