name: 'Detect Changes'
description: 'Detects changes in Docker-related files'

outputs:
  docker_changed:
    description: "Whether Docker-related files were changed"
    value: ${{ steps.check.outputs.docker_changed }}

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        CHANGED=false
        if git diff --name-only HEAD^ HEAD | grep -q "distributions/dockerhub/Dockerfile\|startup/\|.github/workflows/"; then
          CHANGED=true
        fi
        echo "docker_changed=$CHANGED" >> $GITHUB_OUTPUT
