name: Test Workflow Changes

on:
  push:
    paths:
      - '.github/workflows/templates/**'
    branches:
      - 'workflow/**'
      - 'feature/**/workflow'
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow file to test'
        required: true
        type: choice
        options:
          - templates/e2e-integration-test.yml
          - templates/dockerhub-build-and-push.yml
          - templates/bittorrent-build-and-seed.yml
          - templates/create-release.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Workflow Files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
          
      - name: Setup act
        uses: actionsflow/setup-act@v1
        
      - name: Simulate Workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          act -W .github/workflows/templates/${{ github.event.inputs.workflow }} \
              -s GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
              --artifact-server-path /tmp/artifacts \
              -P ubuntu-latest=catthehacker/ubuntu:act-latest

  integration-test:
    needs: validate
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow Integration
        run: |
          # Add integration tests specific to the selected workflow
          echo "Testing ${{ github.event.inputs.workflow }}" 