name: Backend CI

on:

  pull_request:

    branches: [ main ]

    paths:
      - 'projects/**/backend/**'

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull dev environment image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dev-environment:latest

      - name: Run tests in dev environment
        uses: docker:// ${{ secrets.DOCKERHUB_USERNAME }}/dev-environment:latest
        with:
          args: bash -c "cd /
