name: BitTorrent Build and Seed

# Trigger conditions
on:
  push:
    # Only run when specific paths are modified
    paths:
      - 'distributions/bittorrent/**'  # Changes to BitTorrent distribution
      - 'distributions/dockerhub/Dockerfile'  # Base Dockerfile changes
      - 'startup/**'                   # Changes to startup scripts
      - '.github/workflows/**'         # Changes to workflows
      - 'docs/**'                     # Changes to documentation
    branches: [ main, develop ]        # Only on main branches
  pull_request:
    paths:
      - 'distributions/bittorrent/**'
      - 'distributions/dockerhub/Dockerfile'
      - 'startup/**'
      - '.github/workflows/bittorrent-build-and-seed.yml'
    branches: [ main, develop ]
  workflow_dispatch:                   # Manual trigger option

# Required permissions for GitHub Actions
permissions:
  contents: write    # For creating releases
  packages: write    # For package operations
  actions: read      # For workflow access

jobs:
  build-and-seed:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Install required system packages
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y transmission-cli  # Required for torrent operations

      # Copy startup scripts into build context
      # This is necessary because Docker COPY can't access parent directories
      - name: Copy startup scripts to build context
        run: |
          cp -r startup distributions/bittorrent/

      # Build the Docker image
      - name: Build Docker image
        run: |
          cd distributions/bittorrent
          docker build -t dev-environment:latest .
          
      # Save the image as a tar file for distribution
      - name: Save Docker image
        run: |
          cd distributions/bittorrent
          chmod +x scripts/build/save-image.sh
          ./scripts/build/save-image.sh

      # Create and prepare torrent file
      - name: Create and seed torrent
        run: |
          cd distributions/bittorrent
          chmod +x scripts/torrent/create-torrent.sh
          chmod +x scripts/torrent/generate-magnet.sh
          ./scripts/torrent/create-torrent.sh
          ./scripts/torrent/generate-magnet.sh

      # Prepare and upload artifacts for release workflow
      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts/bittorrent
          cp dev-environment.torrent artifacts/bittorrent/
          cp magnet.txt artifacts/bittorrent/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bittorrent-artifacts
          path: artifacts/bittorrent/
          retention-days: 1
