name: Cache Cleanup

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days_old:
        description: 'Delete caches older than X days'
        required: false
        default: '7'
      size_limit_mb:
        description: 'Delete caches larger than X MB'
        required: false
        default: '400'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: cache-cleanup-deps

      - name: Build and run cache cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_DAYS_OLD: ${{ inputs.days_old }}
          INPUT_SIZE_LIMIT_MB: ${{ inputs.size_limit_mb }}
        run: |
          cd workflows/scripts/cache_cleanup
          cargo run --release
