name: Create Comprehensive Release

on:
  workflow_run:
    workflows: ['E2E Integration Tests']
    types:
      - completed
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Verify E2E Test Status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "⛔ E2E tests did not succeed - Release creation blocked"
            echo "Status: ${{ github.event.workflow_run.conclusion }}"
            exit 1
          fi

  create-release:
    needs: verify-e2e
    if: needs.verify-e2e.outputs.should_create == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Distribution Artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          echo "📥 Downloading artifacts from E2E workflow..."
          
          # Download BitTorrent artifacts
          if ! gh run download ${{ github.event.workflow_run.id }} \
            --name bittorrent-artifacts \
            --dir artifacts/bittorrent; then
            echo "❌ Failed to download BitTorrent artifacts"
            exit 1
          fi
            
          # Download DockerHub artifacts
          if ! gh run download ${{ github.event.workflow_run.id }} \
            --name dockerhub-artifacts \
            --dir artifacts/dockerhub; then
            echo "❌ Failed to download DockerHub artifacts"
            exit 1
          fi
          
          echo "✅ Successfully downloaded all artifacts"

      # Verify artifacts are present
      - name: Verify Artifacts
        run: |
          echo "Verifying required artifacts..."
          
          if [ ! -f "artifacts/bittorrent/dev-environment.torrent" ]; then
            echo "❌ BitTorrent torrent file missing"
            exit 1
          fi
          
          if [ ! -f "artifacts/bittorrent/magnet.txt" ]; then
            echo "❌ BitTorrent magnet link file missing"
            exit 1
          fi
          
          if [ ! -f "artifacts/dockerhub/image-info.json" ]; then
            echo "❌ DockerHub image info missing"
            exit 1
          fi
          
          echo "✅ All required artifacts present"

      # Generate release notes
      - name: Generate Release Notes
        run: |
          {
            echo "# 🚀 Development Environment Release"
            echo ""
            echo "## ⚠️ Important Notes"
            echo "- This is an automated release of the development environment"
            echo "- Distribution methods have varying reliability:"
            echo "  - DockerHub: Subject to Docker's rate limiting policies"
            echo "  - BitTorrent: Dependent on peer availability and network conditions"
            echo "- Users should not rely solely on this repository for production environments"
            echo "- Consider building and hosting your own images for commercial use"
            echo ""
            echo "## 🔄 Distribution Methods"
            echo ""
            echo "### DockerHub Distribution"
            echo "- Image: \`cmoe640/dev-environment:${GITHUB_SHA}\`"
            echo "- Status: Available (subject to rate limits)"
            echo "- Pull Command: \`docker pull cmoe640/dev-environment:${GITHUB_SHA}\`"
            echo ""
            echo "### BitTorrent Distribution"
            echo "- Magnet Link: $(cat artifacts/bittorrent/magnet.txt)"
            echo "- Torrent File: Attached to this release"
            echo "- Status: Experimental"
            echo ""
            echo "## 🛠️ Included Tools"
            echo "$(cat artifacts/dockerhub/image-info.json | jq -r '.tools')"
            echo ""
            echo "## 📝 Usage Notes"
            echo "- For personal/development use only"
            echo "- Test thoroughly before using in any production environment"
            echo "- Consider security implications of using pre-built environments"
            echo ""
            echo "## 🔍 Verification"
            echo "- E2E Tests Passed: ✅"
            echo "- Build Date: $(date -u +"%Y-%m-%d %H:%M UTC")"
            echo "- Commit: ${GITHUB_SHA}"
          } > RELEASE_NOTES.md

      # Create GitHub release
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(date +%Y%m%d%H%M)
          gh release create "v${VERSION}" \
            --title "Development Environment v${VERSION}" \
            --notes-file RELEASE_NOTES.md \
            artifacts/bittorrent/dev-environment.torrent \
            artifacts/dockerhub/image-info.json

      # Cleanup
      - name: Cleanup
        if: always()
        run: rm -rf artifacts 

  notify-skip:
    needs: verify-e2e
    if: needs.verify-e2e.outputs.should_create == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Log Skip Reason
        run: |
          echo "⚠️ Release creation was skipped"
          echo "Reason: ${{ needs.verify-e2e.outputs.skip_reason }}"
          echo "Please check the E2E test workflow for details" 