name: E2E Integration Tests

# Trigger on completion of distribution workflows
on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types: [completed]
    branches: [main, develop]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (
        (github.event.workflow_run.workflow == 'DockerHub Build and Push' && github.event.workflow_run.workflow != 'BitTorrent Build and Seed') ||
        (github.event.workflow_run.workflow == 'BitTorrent Build and Seed' && github.event.workflow_run.workflow != 'DockerHub Build and Push')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      # Install required tools for BitTorrent testing
      - name: Install BitTorrent tools
        run: |
          sudo apt-get update
          sudo apt-get install -y transmission-cli

      # Download artifacts from previous workflows
      - name: Download BitTorrent Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bittorrent-artifacts
          path: distributions/bittorrent/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      # Verify BitTorrent artifacts
      - name: Verify BitTorrent Artifacts
        run: |
          echo "📦 Verifying BitTorrent artifacts..."
          if [ ! -f "distributions/bittorrent/artifacts/dev-environment.torrent" ]; then
            echo "❌ Torrent file missing"
            exit 1
          fi
          if [ ! -f "distributions/bittorrent/artifacts/magnet.txt" ]; then
            echo "❌ Magnet link file missing"
            exit 1
          fi
          if [ ! -f "distributions/bittorrent/artifacts/checksum.txt" ]; then
            echo "❌ Checksum file missing"
            exit 1
          fi
          echo "✅ BitTorrent artifacts verified"

      # Test DockerHub distribution method
      - name: Test DockerHub Distribution
        id: dockerhub
        run: |
          chmod +x distributions/dockerhub/e2e/scripts/test.sh
          ./distributions/dockerhub/e2e/scripts/test.sh

      # Test BitTorrent distribution method with artifacts
      - name: Test BitTorrent Distribution
        id: bittorrent
        run: |
          chmod +x distributions/bittorrent/e2e/scripts/test.sh
          chmod +x startup/start-dev.sh
          
          # Ensure we're using BitTorrent distribution
          export PREFER_BITTORRENT=true
          
          # Test start-dev.sh directly first
          echo "🧪 Testing start-dev.sh directly..."
          if ! ./startup/start-dev.sh --test-mode; then
            echo "❌ start-dev.sh verification failed"
            exit 1
          fi
          
          # Run the BitTorrent E2E test suite
          if ! ./distributions/bittorrent/e2e/scripts/test.sh; then
            echo "❌ BitTorrent distribution test failed"
            exit 1
          fi

      # Test distribution switching mechanism
      - name: Test Distribution Switching
        id: switching
        run: |
          chmod +x startup/e2e/scripts/test-distribution-switch.sh
          ./startup/e2e/scripts/test-distribution-switch.sh

      # Report results
      - name: Report Test Results
        if: always()
        run: |
          mkdir -p artifacts/tests
          {
            echo "📊 E2E Test Summary ($(date -u))"
            echo "=================="
            echo "DockerHub Distribution: ${{ steps.dockerhub.outcome }}"
            echo "BitTorrent Distribution: ${{ steps.bittorrent.outcome }}"
            echo "Distribution Switching: ${{ steps.switching.outcome }}"
            echo ""
            echo "🔍 Test Details"
            echo "-------------"
            if [ -f distributions/bittorrent/artifacts/magnet.txt ]; then
              echo "BitTorrent Magnet Link: $(cat distributions/bittorrent/artifacts/magnet.txt)"
            fi
            echo "Docker Images Present:"
            docker images | grep "dev-environment" || echo "No dev-environment images found"
          } | tee artifacts/tests/summary.txt

      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: artifacts/tests/
          retention-days: 1 