name: E2E Integration Tests

on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [ main, develop ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-prerequisites:
    runs-on: ubuntu-latest
    outputs:
      can_proceed: ${{ steps.check.outputs.can_proceed }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - id: check
        name: Check Distribution Workflow States
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.workflow_run.head_branch;
            
            console.log('🔍 Checking distribution workflow states...');
            
            const dockerhubRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'dockerhub-build-and-push.yml',
              branch,
              per_page: 1
            });
            
            const bittorrentRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'bittorrent-build-and-seed.yml',
              branch,
              per_page: 1
            });
            
            const dockerStatus = dockerhubRun.data.workflow_runs[0]?.conclusion;
            const bittorrentStatus = bittorrentRun.data.workflow_runs[0]?.conclusion;
            
            console.log(`📊 Workflow Status Summary:
            - DockerHub: ${dockerStatus || 'not found'}
            - BitTorrent: ${bittorrentStatus || 'not found'}`);
            
            if (!dockerStatus || !bittorrentStatus) {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'Not all distribution workflows have completed');
              return;
            }
            
            if (dockerStatus !== 'success' || bittorrentStatus !== 'success') {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'One or more distribution workflows failed');
              return;
            }
            
            core.setOutput('can_proceed', 'true');
            core.setOutput('reason', 'All prerequisites met');

  cancel-workflow:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Log Cancellation Reason
        run: |
          echo "⚠️ E2E Integration Tests Cancelled"
          echo "Reason: ${{ needs.check-prerequisites.outputs.reason }}"
          exit 1

  run-tests:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Artifacts from Triggering Workflow
        id: download-artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          WORKFLOW_NAME="${{ needs.wait-for-workflows.outputs.triggering_workflow }}"
          echo "📥 Downloading artifacts from $WORKFLOW_NAME..."
          
          # Get workflow-specific artifact names
          if [[ "$WORKFLOW_NAME" == "DockerHub Build and Push" ]]; then
            ARTIFACT_NAME="dockerhub-artifacts"
            TARGET_DIR="dockerhub"
          else
            ARTIFACT_NAME="bittorrent-artifacts"
            TARGET_DIR="bittorrent"
          fi
          
          if ! gh run download ${{ github.event.workflow_run.id }} \
            --name $ARTIFACT_NAME \
            --dir artifacts/$TARGET_DIR; then
            echo "❌ Failed to download $WORKFLOW_NAME artifacts"
            exit 1
          fi
          
          echo "✅ Successfully downloaded artifacts from $WORKFLOW_NAME"

      # Set final status based on all test results
      - id: set-status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

  finalize:
    needs: [wait-for-workflows, e2e-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set Final Workflow Status
        run: |
          if [ "${{ needs.wait-for-workflows.outputs.workflow_status }}" = "skipped" ]; then
            echo "⏭️ E2E tests were skipped due to failed distribution workflows"
            exit 78  # GitHub's neutral exit code
          elif [ "${{ needs.e2e-tests.outputs.test_status }}" != "success" ]; then
            echo "❌ E2E tests failed"
            exit 1
          else
            echo "✅ E2E tests completed successfully"
          fi 