name: E2E Integration Tests

# This workflow runs integration tests for all distribution methods.
# It triggers only after ALL distribution workflows have completed successfully.
#
# To add a new distribution method:
# 1. Add your distribution workflow name to the 'workflows' list below
# 2. Add a new test step in the 'Distribution Tests' section
# 3. Update the test results reporting to include your new distribution

on:
  workflow_run:
    # Add new distribution workflow names here
    workflows: 
      - 'DockerHub Build and Push'
      - 'BitTorrent Build and Seed'
    types: [completed]
    branches: [main, develop]

jobs:
  # First job: Check if all distribution workflows have succeeded
  verify-distributions:
    runs-on: ubuntu-latest
    outputs:
      all_succeeded: ${{ steps.verify.outputs.all_succeeded }}
    steps:
      - id: verify
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Distribution workflows to check
          # Add new workflows to this array when adding new distribution methods
          WORKFLOWS=(
            "dockerhub-build-and-push.yml"
            "bittorrent-build-and-seed.yml"
          )
          
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          echo "Checking workflow runs for branch: $BRANCH"
          
          # Check status of each workflow
          ALL_SUCCEEDED=true
          for workflow in "${WORKFLOWS[@]}"; do
            STATUS=$(gh api \
              "/repos/${{ github.repository }}/actions/workflows/${workflow}/runs?branch=$BRANCH&status=completed&per_page=1" \
              --jq '.workflow_runs[0].conclusion')
            
            echo "Status for ${workflow}: ${STATUS}"
            if [ "$STATUS" != "success" ]; then
              ALL_SUCCEEDED=false
              break
            fi
          done
          
          echo "all_succeeded=${ALL_SUCCEEDED}" >> $GITHUB_OUTPUT

  # Second job: Run the actual E2E tests
  e2e-tests:
    needs: verify-distributions
    if: needs.verify-distributions.outputs.all_succeeded == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # Install dependencies
      # Add new tool installations here if needed for new distribution methods
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y transmission-cli

      # Distribution Tests
      # Add new distribution test steps here
      - name: Test DockerHub Distribution
        id: dockerhub
        run: |
          chmod +x distributions/dockerhub/e2e/scripts/test.sh
          ./distributions/dockerhub/e2e/scripts/test.sh

      - name: Test BitTorrent Distribution
        id: bittorrent
        run: |
          chmod +x distributions/bittorrent/e2e/scripts/test.sh
          export PREFER_BITTORRENT=true
          ./distributions/bittorrent/e2e/scripts/test.sh

      # Cross-distribution Tests
      - name: Test Distribution Switching
        id: switching
        run: |
          chmod +x startup/e2e/scripts/test-distribution-switch.sh
          ./startup/e2e/scripts/test-distribution-switch.sh

      # Results Reporting
      # Add new distribution results to the summary when adding new methods
      - name: Report Test Results
        if: always()
        run: |
          mkdir -p artifacts/tests
          {
            echo "📊 E2E Test Summary"
            echo "=================="
            echo "Distribution Tests:"
            echo "- DockerHub: ${{ steps.dockerhub.outcome }}"
            echo "- BitTorrent: ${{ steps.bittorrent.outcome }}"
            echo ""
            echo "Cross-distribution Tests:"
            echo "- Distribution Switching: ${{ steps.switching.outcome }}"
          } > artifacts/tests/summary.txt

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: artifacts/tests/
          retention-days: 1 