name: E2E Integration Tests

# Trigger on completion of distribution workflows
on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [main, develop]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      # Install required tools for BitTorrent testing
      - name: Install BitTorrent tools
        run: |
          sudo apt-get update
          sudo apt-get install -y transmission-cli

      # Download artifacts from previous workflows
      - name: Download BitTorrent Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bittorrent-artifacts
          path: artifacts/bittorrent

      # Test DockerHub distribution method
      - name: Test DockerHub Distribution
        id: dockerhub
        run: |
          chmod +x distributions/dockerhub/e2e/scripts/test.sh
          ./distributions/dockerhub/e2e/scripts/test.sh

      # Test BitTorrent distribution method
      - name: Test BitTorrent Distribution
        id: bittorrent
        run: |
          chmod +x distributions/bittorrent/e2e/scripts/test.sh
          chmod +x startup/start-dev.sh
          
          # Test direct BitTorrent download
          export PREFER_BITTORRENT=true
          ./startup/start-dev.sh
          
          # Run the full BitTorrent E2E test suite
          ./distributions/bittorrent/e2e/scripts/test.sh

      # Test distribution switching mechanism
      - name: Test Distribution Switching
        id: switching
        run: |
          chmod +x startup/e2e/scripts/test-distribution-switch.sh
          ./startup/e2e/scripts/test-distribution-switch.sh

      # Report results
      - name: Report Test Results
        if: always()
        run: |
          echo "📊 E2E Test Summary"
          echo "=================="
          echo "DockerHub Distribution: ${{ steps.dockerhub.outcome }}"
          echo "BitTorrent Distribution: ${{ steps.bittorrent.outcome }}"
          echo "Distribution Switching: ${{ steps.switching.outcome }}"

      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: artifacts/tests/
          retention-days: 1 