name: E2E Integration Tests

on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [ main, develop ]
    
# Add permissions block
permissions:
  actions: write    # Required for cancelling workflows
  contents: read    # Required for checkout
  packages: read    # Required for artifact access

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  check-prerequisites:
    runs-on: ubuntu-latest
    outputs:
      can_proceed: ${{ steps.check.outputs.can_proceed }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - name: Wait for Artifact Availability
        run: |
          echo "⏳ Waiting for artifacts to be available..."
          sleep 30  # Add 30-second delay

      - id: check
        name: Check Distribution Workflow States
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            
            console.log('🔍 Starting distribution workflow state check...');
            console.log(`Repository: ${owner}/${repo}`);
            console.log(`Workflow Run ID: ${context.payload.workflow_run.id}`);
            console.log(`Head SHA: ${context.payload.workflow_run.head_sha}`);
            
            // Check for artifacts
            console.log('📦 Checking for artifacts...');
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: context.payload.workflow_run.id
            });
            
            console.log('Found artifacts:', artifacts.data.artifacts.map(a => a.name));
            
            const hasDockerArtifacts = artifacts.data.artifacts.some(a => a.name === 'dockerhub-artifacts');
            const hasBitTorrentArtifacts = artifacts.data.artifacts.some(a => a.name === 'bittorrent-artifacts');
            
            console.log(`📊 Detailed Artifact Status:
            - DockerHub: ${hasDockerArtifacts ? '✅' : '❌'} (${hasDockerArtifacts ? 'Found' : 'Not Found'})
            - BitTorrent: ${hasBitTorrentArtifacts ? '✅' : '❌'} (${hasBitTorrentArtifacts ? 'Found' : 'Not Found'})`);
            
            if (!hasDockerArtifacts || !hasBitTorrentArtifacts) {
              console.log('⚠️ Missing artifacts, checking workflow states...');
              // Rest of the checks...

  cancel-workflow:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Log Cancellation
        run: |
          echo "⭕ E2E Integration Tests Cancelled"
          echo "Reason: ${{ needs.check-prerequisites.outputs.reason }}"

      - name: Cancel Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            await github.rest.actions.cancelWorkflowRun({
              owner,
              repo,
              run_id: context.runId
            });
            
            console.log('Workflow cancellation requested');

  run-tests:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ steps.test-result.outputs.status }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Distribution Artifacts
        id: download-artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          echo "📥 Attempting to download artifacts from workflow run ${{ github.event.workflow_run.id }}"
          
          ARTIFACTS_MISSING=false
          
          echo "Checking BitTorrent artifacts..."
          if gh run download ${{ github.event.workflow_run.id }} \
            --name bittorrent-artifacts \
            --dir artifacts/bittorrent; then
            echo "✅ BitTorrent artifacts downloaded successfully"
          else
            echo "❌ BitTorrent artifacts missing"
            ARTIFACTS_MISSING=true
          fi
            
          echo "Checking DockerHub artifacts..."
          if gh run download ${{ github.event.workflow_run.id }} \
            --name dockerhub-artifacts \
            --dir artifacts/dockerhub; then
            echo "✅ DockerHub artifacts downloaded successfully"
          else
            echo "❌ DockerHub artifacts missing"
            ARTIFACTS_MISSING=true
          fi
          
          if [ "$ARTIFACTS_MISSING" = "true" ]; then
            echo "❌ Error: One or more required artifacts are missing"
            exit 1
          fi
          
          echo "✅ All required artifacts downloaded successfully"

      - id: test-result
        name: Set Test Result
        if: always()
        run: |
          if [ "${{ steps.download-artifacts.outcome }}" = "success" ]; then
            echo "✅ Artifact download successful"
            echo "📊 Found Artifacts:"
            [ "${{ steps.download-artifacts.outputs.bittorrent_found }}" = "true" ] && echo "- BitTorrent"
            [ "${{ steps.download-artifacts.outputs.dockerhub_found }}" = "true" ] && echo "- DockerHub"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Artifact download failed"
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

  finalize:
    needs: [check-prerequisites, run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set Final Status
        run: |
          if [ "${{ needs.check-prerequisites.outputs.can_proceed }}" != "true" ]; then
            echo "⚠ E2E tests cancelled: ${{ needs.check-prerequisites.outputs.reason }}"
            exit 78  # Neutral exit code for cancelled state
          elif [ "${{ needs.run-tests.result }}" != "success" ]; then
            echo "❌ E2E tests failed"
            exit 1
          else
            echo "✅ E2E tests completed successfully"
          fi 