name: E2E Integration Tests

on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [ main, develop ]
    
# Add permissions block
permissions:
  actions: write    # Required for cancelling workflows
  contents: read    # Required for checkout
  packages: read    # Required for artifact access

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-prerequisites:
    runs-on: ubuntu-latest
    outputs:
      can_proceed: ${{ steps.check.outputs.can_proceed }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - id: check
        name: Check Distribution Workflow States
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.workflow_run.head_branch;
            
            console.log('🔍 Checking distribution workflow states...');
            
            // Check DockerHub workflow
            const dockerhubRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'dockerhub-build-and-push.yml',
              branch,
              per_page: 1
            });
            
            // Check BitTorrent workflow
            const bittorrentRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'bittorrent-build-and-seed.yml',
              branch,
              per_page: 1
            });
            
            // Check artifact existence
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: context.payload.workflow_run.id
            });
            
            const hasDockerArtifacts = artifacts.data.artifacts.some(a => a.name === 'dockerhub-artifacts');
            const hasBitTorrentArtifacts = artifacts.data.artifacts.some(a => a.name === 'bittorrent-artifacts');
            
            console.log(`📦 Artifact Status:
            - DockerHub: ${hasDockerArtifacts ? '✅' : '❌'}
            - BitTorrent: ${hasBitTorrentArtifacts ? '✅' : '❌'}`);
            
            if (!hasDockerArtifacts || !hasBitTorrentArtifacts) {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'Required artifacts are missing');
              return;
            }
            
            const dockerStatus = dockerhubRun.data.workflow_runs[0]?.conclusion;
            const bittorrentStatus = bittorrentRun.data.workflow_runs[0]?.conclusion;
            
            console.log(`📊 Workflow Status Summary:
            - DockerHub: ${dockerStatus || 'not found'}
            - BitTorrent: ${bittorrentStatus || 'not found'}`);
            
            if (!dockerStatus || !bittorrentStatus) {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'Waiting for all distribution workflows to complete');
              return;
            }
            
            if (dockerStatus !== 'success' || bittorrentStatus !== 'success') {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'One or more distribution workflows failed');
              return;
            }
            
            core.setOutput('can_proceed', 'true');
            core.setOutput('reason', 'All prerequisites met');

  cancel-workflow:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Log Cancellation
        run: |
          echo "⭕ E2E Integration Tests Cancelled"
          echo "Reason: ${{ needs.check-prerequisites.outputs.reason }}"

      - name: Cancel Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            await github.rest.actions.cancelWorkflowRun({
              owner,
              repo,
              run_id: context.runId
            });
            
            console.log('Workflow cancellation requested');

  run-tests:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ steps.test-result.outputs.status }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Distribution Artifacts
        id: download-artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          echo "📥 Attempting to download artifacts from workflow run ${{ github.event.workflow_run.id }}"
          
          ARTIFACTS_MISSING=false
          
          echo "Checking BitTorrent artifacts..."
          if gh run download ${{ github.event.workflow_run.id }} \
            --name bittorrent-artifacts \
            --dir artifacts/bittorrent; then
            echo "✅ BitTorrent artifacts downloaded successfully"
          else
            echo "❌ BitTorrent artifacts missing"
            ARTIFACTS_MISSING=true
          fi
            
          echo "Checking DockerHub artifacts..."
          if gh run download ${{ github.event.workflow_run.id }} \
            --name dockerhub-artifacts \
            --dir artifacts/dockerhub; then
            echo "✅ DockerHub artifacts downloaded successfully"
          else
            echo "❌ DockerHub artifacts missing"
            ARTIFACTS_MISSING=true
          fi
          
          if [ "$ARTIFACTS_MISSING" = "true" ]; then
            echo "❌ Error: One or more required artifacts are missing"
            exit 1
          fi
          
          echo "✅ All required artifacts downloaded successfully"

      - id: test-result
        name: Set Test Result
        if: always()
        run: |
          if [ "${{ steps.download-artifacts.outcome }}" = "success" ]; then
            echo "✅ Artifact download successful"
            echo "📊 Found Artifacts:"
            [ "${{ steps.download-artifacts.outputs.bittorrent_found }}" = "true" ] && echo "- BitTorrent"
            [ "${{ steps.download-artifacts.outputs.dockerhub_found }}" = "true" ] && echo "- DockerHub"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Artifact download failed"
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

  finalize:
    needs: [check-prerequisites, run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set Final Status
        run: |
          if [ "${{ needs.check-prerequisites.outputs.can_proceed }}" != "true" ]; then
            echo "⚠ E2E tests cancelled: ${{ needs.check-prerequisites.outputs.reason }}"
            exit 78  # Neutral exit code for cancelled state
          elif [ "${{ needs.run-tests.result }}" != "success" ]; then
            echo "❌ E2E tests failed"
            exit 1
          else
            echo "✅ E2E tests completed successfully"
          fi 