name: E2E Integration Tests

# This workflow runs integration tests for all distribution methods.
# It triggers only after ALL distribution workflows have completed successfully.
#
# To add a new distribution method:
# 1. Add your distribution workflow name to the 'workflows' list below
# 2. Add a new test step in the 'Distribution Tests' section
# 3. Update the test results reporting to include your new distribution

on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [ main, develop ]

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      should_run: ${{ steps.check-workflows.outputs.should_run }}
    steps:
      - id: check-workflows
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.workflow_run.head_branch;
            
            // Get the latest runs of both workflows
            const dockerhubRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'dockerhub-build-and-push.yml',
              branch,
              per_page: 1
            });
            
            const bittorrentRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'bittorrent-build-and-seed.yml',
              branch,
              per_page: 1
            });
            
            // Check if both workflows have completed successfully
            const shouldRun = 
              dockerhubRun.data.workflow_runs[0]?.conclusion === 'success' &&
              bittorrentRun.data.workflow_runs[0]?.conclusion === 'success';
            
            core.setOutput('should_run', shouldRun);

  e2e-tests:
    needs: wait-for-workflows
    if: needs.wait-for-workflows.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # Download artifacts from both distribution workflows
      - name: Download Distribution Artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          # Download BitTorrent artifacts
          gh run download ${{ github.event.workflow_run.id }} \
            --name bittorrent-artifacts \
            --dir artifacts/bittorrent
            
          # Download DockerHub artifacts
          gh run download ${{ github.event.workflow_run.id }} \
            --name dockerhub-artifacts \
            --dir artifacts/dockerhub

      # Run BitTorrent distribution tests
      - name: Run BitTorrent Tests
        run: |
          chmod +x distributions/bittorrent/e2e/scripts/test.sh
          ./distributions/bittorrent/e2e/scripts/test.sh

      # Run DockerHub distribution tests
      - name: Run DockerHub Tests
        run: |
          chmod +x distributions/dockerhub/e2e/scripts/test.sh
          ./distributions/dockerhub/e2e/scripts/test.sh

      # Run cross-distribution tests
      - name: Run Distribution Switch Tests
        run: |
          chmod +x startup/e2e/scripts/test-distribution-switch.sh
          ./startup/e2e/scripts/test-distribution-switch.sh

      # Generate test summary
      - name: Generate Test Summary
        run: |
          mkdir -p artifacts/tests
          {
            echo "📊 E2E Test Summary"
            echo "=================="
            echo "Distribution Tests:"
            echo "- DockerHub: ✅"
            echo "- BitTorrent: ✅"
            echo ""
            echo "Cross-distribution Tests:"
            echo "- Distribution Switching: ✅"
          } > artifacts/tests/summary.txt

      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: artifacts/tests/
          retention-days: 1 