name: E2E Integration Tests

on:
  workflow_run:
    workflows: ['DockerHub Build and Push', 'BitTorrent Build and Seed']
    types:
      - completed
    branches: [ main, develop ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-prerequisites:
    runs-on: ubuntu-latest
    outputs:
      can_proceed: ${{ steps.check.outputs.can_proceed }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - id: check
        name: Check Distribution Workflow States
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.workflow_run.head_branch;
            
            console.log('🔍 Checking distribution workflow states...');
            
            const dockerhubRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'dockerhub-build-and-push.yml',
              branch,
              per_page: 1
            });
            
            const bittorrentRun = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'bittorrent-build-and-seed.yml',
              branch,
              per_page: 1
            });
            
            const dockerStatus = dockerhubRun.data.workflow_runs[0]?.conclusion;
            const bittorrentStatus = bittorrentRun.data.workflow_runs[0]?.conclusion;
            
            console.log(`📊 Workflow Status Summary:
            - DockerHub: ${dockerStatus || 'not found'}
            - BitTorrent: ${bittorrentStatus || 'not found'}`);
            
            if (!dockerStatus || !bittorrentStatus) {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'Waiting for all distribution workflows to complete');
              return;
            }
            
            if (dockerStatus !== 'success' || bittorrentStatus !== 'success') {
              core.setOutput('can_proceed', 'false');
              core.setOutput('reason', 'One or more distribution workflows failed');
              return;
            }
            
            core.setOutput('can_proceed', 'true');
            core.setOutput('reason', 'All prerequisites met');

  cancel-workflow:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow
        run: |
          echo "⭕ E2E Integration Tests Cancelled"
          echo "Reason: ${{ needs.check-prerequisites.outputs.reason }}"
          exit 78  # GitHub's neutral exit code for cancelled state

  run-tests:
    needs: check-prerequisites
    if: needs.check-prerequisites.outputs.can_proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ steps.test-result.outputs.status }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Distribution Artifacts
        id: download-artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts/{bittorrent,dockerhub}
          
          echo "📥 Downloading artifacts from workflow run ${{ github.event.workflow_run.id }}"
          
          ARTIFACTS_FOUND=false
          
          # Try to download BitTorrent artifacts
          if gh run download ${{ github.event.workflow_run.id }} \
            --name bittorrent-artifacts \
            --dir artifacts/bittorrent; then
            ARTIFACTS_FOUND=true
          else
            echo "⚠️ No BitTorrent artifacts found"
          fi
            
          # Try to download DockerHub artifacts
          if gh run download ${{ github.event.workflow_run.id }} \
            --name dockerhub-artifacts \
            --dir artifacts/dockerhub; then
            ARTIFACTS_FOUND=true
          else
            echo "⚠️ No DockerHub artifacts found"
          fi
          
          if [ "$ARTIFACTS_FOUND" = "false" ]; then
            echo "❌ No artifacts found from either workflow"
            exit 1
          fi
          
          echo "✅ Successfully downloaded available artifacts"

      - id: test-result
        name: Set Test Result
        if: always()
        run: |
          if [ "${{ steps.download-artifacts.outcome }}" = "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

  finalize:
    needs: [check-prerequisites, run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set Final Status
        run: |
          if [ "${{ needs.check-prerequisites.outputs.can_proceed }}" != "true" ]; then
            echo "⚠ E2E tests cancelled: ${{ needs.check-prerequisites.outputs.reason }}"
            exit 78  # Neutral exit code for cancelled state
          elif [ "${{ needs.run-tests.result }}" != "success" ]; then
            echo "❌ E2E tests failed"
            exit 1
          else
            echo "✅ E2E tests completed successfully"
          fi 