name: Setup Docker Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Docker image tag to use"
        value: ${{ jobs.setup.outputs.image_tag }}
      base_image_ready:
        description: "Whether base image exists"
        value: ${{ jobs.setup.outputs.base_image_ready }}
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      image_tag: ${{ steps.check_image.outputs.image_tag }}
      base_image_ready: ${{ steps.check_image.outputs.exists }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build workflow scripts
        run: |
          cd .github/scripts
          cargo build --release

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check Base Image
        id: check_image
        env:
          INPUT_TAG: "cmoe640/dev-environment:${{ inputs.environment }}"
        run: |
          cd .github/scripts
          ./target/release/step-check-base-image

      - name: Setup Docker Environment
        if: steps.check_image.outputs.exists != 'true'
        id: setup_docker
        run: |
          cd .github/scripts
          ./target/release/step-setup-docker-env

      - name: Setup Docker Buildx
        if: steps.check_image.outputs.exists != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        if: steps.check_image.outputs.exists != 'true'
        env:
          INPUT_TAG: "cmoe640/dev-environment:${{ inputs.environment }}"
          INPUT_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          cd .github/scripts
          ./target/release/step-build-image

      - name: Report Setup Status
        run: |
          echo "## 🐳 Docker Setup Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Environment Status" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${GITHUB_REF#refs/heads/}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: \`${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Image: \`${{ steps.check_image.outputs.image_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Status: \`${{ steps.check_image.outputs.exists }}\`" >> $GITHUB_STEP_SUMMARY
