name: Cleanup on Failure

on:
  workflow_call:
    secrets:
      BOT_GITHUB_TOKEN:
        required: true
      BOT_GPG_PRIVATE_KEY:
        required: true
      BOT_GPG_PASSPHRASE:
        required: true
      BOT_EMAIL:
        required: true
      BOT_NAME:
        required: true
      BOT_DOMAIN:
        required: true

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  deployments: write
  issues: write
  repository-projects: write
  statuses: write

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Revert commit
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_DOMAIN: ${{ secrets.BOT_DOMAIN }}
        run: |
          git config user.name "${BOT_NAME}"
          git config user.email "${BOT_EMAIL}@${BOT_DOMAIN}"
          git revert --signoff -S ${{ github.sha }} --no-edit
          git push

      - name: Create failure report
        if: always()
        run: |
          echo "## 🚨 Pipeline Failure Report" >> $GITHUB_STEP_SUMMARY
          echo "Automatic revert was triggered due to pipeline failure" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Details" >> $GITHUB_STEP_SUMMARY
          echo "- Failed commit: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Triggered by: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Review pipeline logs for error details" >> $GITHUB_STEP_SUMMARY
          echo "2. Fix identified issues" >> $GITHUB_STEP_SUMMARY
          echo "3. Re-submit changes in a new commit" >> $GITHUB_STEP_SUMMARY

      - name: Notify about revert
        run: |
          echo "::notice title=Pipeline Failure::Changes were automatically reverted due to pipeline failure. See summary for details."
