name: Detect Changes

on:
  workflow_call:
    outputs:
      docker_changed:
        description: "Whether Docker-related files were changed"
        value: ${{ jobs.check.outputs.docker_changed }}

jobs:
  check:
    runs-on: ubuntu-22.04
    outputs:
      docker_changed: ${{ steps.check.outputs.docker_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check for Dockerfile changes
        id: check
        run: |
          CHANGED=false
          if git diff --name-only HEAD^ HEAD | grep -q "distributions/dockerhub/Dockerfile\|startup/\|.github/workflows/"; then
            CHANGED=true
          fi
          echo "docker_changed=$CHANGED" >> $GITHUB_OUTPUT
