name: Release Queue Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Queue action (list/clear/prioritize)'
        required: true
        type: choice
        options:
          - list
          - clear
          - prioritize

jobs:
  manage_queue:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manage-release-queue
        with:
          action: ${{ github.event.inputs.action }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
