name: Create Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - beta
      - 'release-*'
  pull_request:
    branches:
      - main
      - beta
      - 'release-*'
    paths:
      - '.github/workflows/create_release.yml'
      - 'version.txt'
      - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release:
    uses: ./.github/workflows/job_create_release.yml
    with:
      version: ${{ inputs.version }}
      prerelease: ${{ inputs.prerelease }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      BOT_GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
      BOT_GPG_PASSPHRASE: ${{ secrets.BOT_GPG_PASSPHRASE }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      BOT_NAME: ${{ secrets.BOT_NAME }}
      BOT_DOMAIN: ${{ secrets.BOT_DOMAIN }}
